### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Kr0nox** [NamelessGroup/AdventOfCode-CLI#2]
I am in favor of writing a proper documentation for at least all files that other developers interact with.
This is most important for Language.

I would also like to put forward looking into naming variables more fitting (e.g.: sourcePath in Language.getRunCwd sounds like it is given ../src but is actually given ../src/dayXX)

**Comment by c0derMo** [comment]
Documentation was previously hastily written to allow for quick release, and is certainly something that needs work, will do in the near future.

**Comment by Kr0nox** [comment]
isn't this done?
